const data = {
  products: [
    {
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descrition: "hight qualuty shirts",
    },
    {
      name: "Adidas Slim Shirt",
      slug: "adidas-slim-shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 250,
      countInStock: 0,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      descrition: "hight qualuty shirts",
    },
    {
      name: "Nike Slim pants",
      slug: "nike-slim-pants",
      category: "Pants",
      image: "/images/p3.jpg",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      descrition: "hight qualuty shirts",
    },

    {
      name: "Adidas Slim Pant",
      slug: "adidas-slim-pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 120,
      countInStock: 10,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      descrition: "hight qualuty shirts",
    },
  ],
};
export default data;
